import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFExportOptions {
    title: string;
    executiveSummary?: string;
    sections?: Array<{ heading: string; content: string }>;
    insights?: Array<{ finding: string; impact: string; confidence: string }>;
    charts?: Array<{ title: string; description: string; chartType: string }>;
    recommendations?: string[];
    nextSteps?: string[];
    metadata?: {
        generatedAt: Date;
        analysisId: string;
        reportType: string;
    };
}

export class ProfessionalPDFExporter {
    private pdf: jsPDF;
    private yPosition: number;
    private pageHeight: number;
    private pageWidth: number;
    private margin: number;
    private lineHeight: number;
    private primaryColor: [number, number, number] = [30, 50, 80]; // Academic Navy
    private secondaryColor: [number, number, number] = [40, 40, 40]; // Dark Gray/Black
    private accentColor: [number, number, number] = [200, 200, 200]; // Subtle Gray

    constructor() {
        this.pdf = new jsPDF('p', 'mm', 'a4');
        this.yPosition = 20;
        this.pageHeight = 297; // A4 height in mm
        this.pageWidth = 210; // A4 width in mm
        this.margin = 20;
        this.lineHeight = 7;
    }

    async generateReport(options: PDFExportOptions): Promise<void> {
        // Cover Page
        this.addCoverPage(options.title, options.metadata);

        // Table of Contents
        this.addNewPage();
        this.addTableOfContents(options);

        // Executive Summary (Abstract)
        if (options.executiveSummary) {
            this.addNewPage();
            this.addExecutiveSummary(options.executiveSummary);
        }

        // Detailed Analysis Sections (Introduction, Methods, Results, etc.)
        if (options.sections && options.sections.length > 0) {
            options.sections.forEach((section, index) => {
                // Always start major sections on a new page if they are large, or just ensure spacing
                if (index > 0 && this.yPosition > 220) {
                    this.addNewPage();
                } else if (index > 0) {
                    this.yPosition += 10;
                }
                this.addAnalysisSection(section.heading, section.content);
            });
        }

        // Visualizations
        if (options.charts && options.charts.length > 0) {
            this.addNewPage();
            await this.addVisualizations(options.charts);
        }

        // Recommendations (if any)
        if (options.recommendations && options.recommendations.length > 0) {
            this.addNewPage();
            this.addRecommendations(options.recommendations);
        }

        // Next Steps (if any)
        if (options.nextSteps && options.nextSteps.length > 0) {
            this.addNextSteps(options.nextSteps);
        }

        // Footer on all pages
        this.addPageNumbers();
    }

    private addCoverPage(title: string, metadata?: PDFExportOptions['metadata']): void {
        // Formal Header Line
        this.pdf.setFillColor(...this.primaryColor);
        this.pdf.rect(0, 0, this.pageWidth, 40, 'F');

        // Title
        this.yPosition = 80;
        this.pdf.setTextColor(0, 0, 0);
        this.pdf.setFontSize(28);
        this.pdf.setFont('helvetica', 'bold');
        const titleLines = this.pdf.splitTextToSize(title, this.pageWidth - 40);
        titleLines.forEach((line: string) => {
            this.pdf.text(line, this.pageWidth / 2, this.yPosition, { align: 'center' });
            this.yPosition += 12;
        });

        // Subtitle
        this.pdf.setFontSize(16);
        this.pdf.setFont('helvetica', 'normal');
        this.pdf.setTextColor(80, 80, 80);
        this.pdf.text('Technical Data Analysis Report', this.pageWidth / 2, this.yPosition + 5, { align: 'center' });

        // Metadata (Simple text, no box)
        this.yPosition = 160;
        this.pdf.setFontSize(11);
        this.pdf.setTextColor(0, 0, 0);

        if (metadata) {
            this.pdf.text(`Date: ${new Date(metadata.generatedAt).toLocaleDateString()}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
            this.yPosition += 8;
            this.pdf.text(`Analysis ID: ${metadata.analysisId}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
            this.yPosition += 8;
            this.pdf.text(`Type: ${metadata.reportType.replace(/_/g, ' ').toUpperCase()}`, this.pageWidth / 2, this.yPosition, { align: 'center' });
        }

        // Footer branding
        this.yPosition = this.pageHeight - 30;
        this.pdf.setFontSize(10);
        this.pdf.setTextColor(150, 150, 150);
        this.pdf.text('Generated by Lumina Analytics', this.pageWidth / 2, this.yPosition, { align: 'center' });
    }

    private addTableOfContents(options: PDFExportOptions): void {
        this.addSectionHeader('Table of Contents');

        const toc = [
            'Abstract',
            ...(options.sections?.map(s => s.heading) || []),
            'Visualizations',
            'Recommendations',
            'Next Steps'
        ].filter(Boolean);

        this.pdf.setFontSize(11);
        this.pdf.setFont('helvetica', 'normal');

        toc.forEach((item, index) => {
            if (!item) return;
            this.checkPageBreak(10);
            this.pdf.setTextColor(...this.secondaryColor);
            this.pdf.text(`${index + 1}. ${item}`, this.margin + 5, this.yPosition);

            // Dotted line leader (Simulated with dots if needed, or just simple spacing)
            // const textWidth = this.pdf.getTextWidth(`${index + 1}. ${item}`);
            // this.pdf.text('................................................................', this.margin + 5 + textWidth + 2, this.yPosition);

            this.yPosition += 8;
        });
    }

    private addExecutiveSummary(summary: string): void {
        this.addSectionHeader('Abstract');
        this.addParagraph(summary);
    }

    // ... (Key Insights removed as they are now part of Results/Conclusion in academic style)

    private async addVisualizations(charts: Array<{ title: string; description: string; chartType: string }>): Promise<void> {
        this.addSectionHeader('Visualizations');

        for (const chart of charts) {
            this.checkPageBreak(80);

            // Chart title (Figure X)
            this.pdf.setFontSize(11);
            this.pdf.setFont('helvetica', 'bold');
            this.pdf.setTextColor(0, 0, 0);
            this.pdf.text(`Figure: ${chart.title}`, this.margin, this.yPosition);
            this.yPosition += 8;

            // Try to capture chart
            try {
                const chartElement = document.querySelector(`[data-chart-title="${chart.title}"]`);
                if (chartElement) {
                    const canvas = await html2canvas(chartElement as HTMLElement, {
                        scale: 2,
                        backgroundColor: '#ffffff'
                    });
                    const imgData = canvas.toDataURL('image/png');
                    const imgWidth = this.pageWidth - 2 * this.margin;
                    const imgHeight = (canvas.height * imgWidth) / canvas.width;

                    this.checkPageBreak(imgHeight + 10);
                    this.pdf.addImage(imgData, 'PNG', this.margin, this.yPosition, imgWidth, imgHeight);
                    this.yPosition += imgHeight + 5;
                } else {
                    // Placeholder - Academic Style
                    this.pdf.setDrawColor(200, 200, 200);
                    this.pdf.rect(this.margin, this.yPosition, this.pageWidth - 2 * this.margin, 60); // Simple border
                    this.pdf.setTextColor(100, 100, 100);
                    this.pdf.setFontSize(10);
                    this.pdf.text(`[Visualization: ${chart.chartType}]`, this.pageWidth / 2, this.yPosition + 30, { align: 'center' });
                    this.yPosition += 65;
                }
            } catch (err) {
                console.error('Chart capture failed:', err);
                this.yPosition += 10;
            }

            // Chart description (Caption)
            this.pdf.setFontSize(10);
            this.pdf.setFont('helvetica', 'italic');
            this.pdf.setTextColor(50, 50, 50);
            const descLines = this.pdf.splitTextToSize(chart.description, this.pageWidth - 2 * this.margin);
            this.pdf.text(descLines, this.margin, this.yPosition);
            this.yPosition += descLines.length * 5 + 10;
        }
    }

    private addAnalysisSection(heading: string, content: string): void {
        this.addSectionHeader(heading);
        this.addParagraph(content);
        this.yPosition += 10;
    }

    private addRecommendations(recommendations: string[]): void {
        this.addSectionHeader('Recommendations');

        recommendations.forEach((rec, index) => {
            this.checkPageBreak(15);

            this.pdf.setTextColor(0, 0, 0);
            this.pdf.setFontSize(10);
            this.pdf.setFont('helvetica', 'normal');
            const recLines = this.pdf.splitTextToSize(`${index + 1}. ${rec}`, this.pageWidth - 2 * this.margin);
            this.pdf.text(recLines, this.margin, this.yPosition);

            this.yPosition += recLines.length * 5 + 5;
        });
    }

    private addNextSteps(steps: string[]): void {
        this.checkPageBreak(50);
        this.addSectionHeader('Next Steps & Action Items');

        steps.forEach((step, index) => {
            this.checkPageBreak(15);

            this.pdf.setFillColor(255, 248, 240);
            this.pdf.roundedRect(this.margin, this.yPosition, this.pageWidth - 2 * this.margin, 12, 1, 1, 'F');

            this.pdf.setTextColor(...this.primaryColor);
            this.pdf.setFontSize(10);
            this.pdf.setFont('helvetica', 'bold');
            const stepLines = this.pdf.splitTextToSize(`${index + 1}. ${step}`, this.pageWidth - 2 * this.margin - 10);
            this.pdf.text(stepLines, this.margin + 5, this.yPosition + 7);

            this.yPosition += 14;
        });
    }

    private addSectionHeader(title: string): void {
        this.checkPageBreak(20);

        // Header bar
        this.pdf.setFillColor(...this.primaryColor);
        this.pdf.rect(this.margin, this.yPosition, 5, 10, 'F');

        this.pdf.setTextColor(...this.secondaryColor);
        this.pdf.setFontSize(16);
        this.pdf.setFont('helvetica', 'bold');
        this.pdf.text(title, this.margin + 10, this.yPosition + 7);

        // Underline
        this.pdf.setDrawColor(...this.primaryColor);
        this.pdf.setLineWidth(0.5);
        this.pdf.line(this.margin, this.yPosition + 12, this.pageWidth - this.margin, this.yPosition + 12);

        this.yPosition += 18;
    }

    private addParagraph(text: string, leftMargin: number = this.margin): void {
        this.pdf.setFontSize(10);
        this.pdf.setFont('helvetica', 'normal');
        this.pdf.setTextColor(...this.secondaryColor);

        const lines = this.pdf.splitTextToSize(text, this.pageWidth - leftMargin - this.margin);
        lines.forEach((line: string) => {
            this.checkPageBreak(this.lineHeight);
            this.pdf.text(line, leftMargin, this.yPosition);
            this.yPosition += this.lineHeight;
        });
        this.yPosition += 3;
    }

    private estimateTextHeight(text: string, width: number): number {
        const lines = this.pdf.splitTextToSize(text, width);
        return lines.length * this.lineHeight;
    }

    private checkPageBreak(requiredSpace: number): void {
        if (this.yPosition + requiredSpace > this.pageHeight - 30) {
            this.addNewPage();
        }
    }

    private addNewPage(): void {
        this.pdf.addPage();
        this.yPosition = this.margin;
    }

    private addPageNumbers(): void {
        const pageCount = this.pdf.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            this.pdf.setPage(i);
            this.pdf.setFontSize(9);
            this.pdf.setTextColor(150, 150, 150);
            this.pdf.text(
                `Page ${i} of ${pageCount}`,
                this.pageWidth / 2,
                this.pageHeight - 10,
                { align: 'center' }
            );
        }
    }

    save(filename: string): void {
        const pdfFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
        console.log('Saving professional PDF as:', pdfFilename);
        this.pdf.save(pdfFilename);
    }

    getBlob(): Blob {
        return this.pdf.output('blob');
    }
}

// Helper function to export Scribe report as professional PDF
export async function exportScribeReportAsPDF(analysisResult: any): Promise<void> {
    try {
        console.log('Starting professional PDF generation...');
        const exporter = new ProfessionalPDFExporter();

        await exporter.generateReport({
            title: analysisResult.reportContent?.title || 'Data Analysis Report',
            executiveSummary: analysisResult.executiveSummary,
            sections: analysisResult.reportContent?.sections || [],
            insights: analysisResult.insights || [],
            charts: analysisResult.generatedCharts || analysisResult.recommendedVisualizations || [],
            recommendations: analysisResult.reportContent?.recommendations || [],
            nextSteps: analysisResult.reportContent?.nextSteps || [],
            metadata: analysisResult.metadata || {
                generatedAt: new Date(),
                analysisId: `RPT-${Date.now()}`,
                reportType: 'comprehensive_analysis'
            }
        });

        const timestamp = new Date().toISOString().split('T')[0];
        const filename = `Data-Analysis-Report-${timestamp}.pdf`;

        exporter.save(filename);

        console.log('✅ Professional PDF generated successfully:', filename);
        return;
    } catch (error) {
        console.error('❌ PDF generation error:', error);
        throw new Error(`Failed to generate PDF: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
}
